//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caso_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deliverable
    {
        public int Id { get; set; }
        public int IdPartido { get; set; }
        public int IdPlan { get; set; }
        public int IdAction { get; set; }
        public int IdCanton { get; set; }
        public int KpiValue { get; set; }
        public string KpiType { get; set; }
        public System.DateTime PostTime { get; set; }
        public string Checksum { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Cantone Cantone { get; set; }
        public virtual Party Party { get; set; }
        public virtual Plane Plane { get; set; }
    }
}
