//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caso_1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Caso_1Entities : DbContext
    {
        public Caso_1Entities()
            : base("name=Caso_1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Action> Actions { get; set; }
        public DbSet<Cantone> Cantones { get; set; }
        public DbSet<Deliverable> Deliverables { get; set; }
        public DbSet<Party> Parties { get; set; }
        public DbSet<Plane> Planes { get; set; }
        public DbSet<Provincia> Provincias { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
    
        public virtual ObjectResult<Consulta_1_Result> Consulta_1(string canton)
        {
            var cantonParameter = canton != null ?
                new ObjectParameter("Canton", canton) :
                new ObjectParameter("Canton", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Consulta_1_Result>("Consulta_1", cantonParameter);
        }
    
        public virtual ObjectResult<string> Consulta_2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Consulta_2");
        }
    }
}
