//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caso_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Party
    {
        public Party()
        {
            this.Deliverables = new HashSet<Deliverable>();
            this.Planes = new HashSet<Plane>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string URLFlag { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual ICollection<Deliverable> Deliverables { get; set; }
        public virtual ICollection<Plane> Planes { get; set; }
    }
}
