//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caso_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plane
    {
        public Plane()
        {
            this.Actions = new HashSet<Action>();
            this.Deliverables = new HashSet<Deliverable>();
        }
    
        public int Id { get; set; }
        public int IdPartido { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Action> Actions { get; set; }
        public virtual ICollection<Deliverable> Deliverables { get; set; }
        public virtual Party Party { get; set; }
    }
}
